services:
  be:
    container_name: tsc-be
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "8168:8168"
    env_file:
      - .env
    volumes:
      - ./uploads:/usr/share/be/uploads
    command: yarn start:dev